Update testbranchupdate

diff --git a/jenkins/testbranchupdate b/jenkins/testbranchupdate
--- a/jenkins/testbranchupdate
+++ b/jenkins/testbranchupdate
@@ -17,7 +17,14 @@ pipeline {
                         git config user.email "sskid12@naver.com"
                         git checkout test
                         git merge dev || (git merge --abort && exit 1)
-                        git push https://${GIT_TOKEN}@github.com/dnrwn/restapi_song.git test
+                        if git status | findstr /i "conflict" ; then
+                            echo "Merge conflicts detected. Aborting merge."
+                            git merge --abort
+                            exit 1
+                        else
+                            echo "Merge successful. Pushing changes to test branch."
+                            git push https://${GIT_TOKEN}@github.com/dnrwn/restapi_song.git test
+                        fi
                     '''
                 }
             }
